// <auto-generated />
using System;
using GiClubSite.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GiClubSite.Migrations
{
    [DbContext(typeof(GiClubSiteContext))]
    [Migration("20230107142353_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GiClubSite.Models.ContactMail", b =>
                {
                    b.Property<int>("ContactMailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CM_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CM_Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CM_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CM_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CM_SendTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CM_University")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactMailId");

                    b.ToTable("ContactMail");
                });

            modelBuilder.Entity("GiClubSite.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("E_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("E_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("E_DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("E_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("GiClubSite.Models.EventFile", b =>
                {
                    b.Property<int>("EventFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EF_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.HasKey("EventFileId");

                    b.HasIndex("EventId");

                    b.ToTable("EventFile");
                });

            modelBuilder.Entity("GiClubSite.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("M_Cellule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("M_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("M_DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("M_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M_FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M_LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M_Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M_Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M_Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("GiClubSite.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("T_Cell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("T_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("T_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T_Notification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T_Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("GiClubSite.Models.EventFile", b =>
                {
                    b.HasOne("GiClubSite.Models.Event", "Event")
                        .WithMany("EventFiles")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("GiClubSite.Models.Event", b =>
                {
                    b.Navigation("EventFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
